### PR TITLE
Move image

### LINKED ISSUE #19: Move and group images from public
since we got folder image under assets please store image there not in public.
also please **group** the image base on where the image is used.

make sure no error happen when you move the files

### PR DESCRIPTION
**Pull request by luthfi-ramadhan**
Moving and grouping image 
#19 

@azhry @rizkipraatama @LordDoraemon

### CODE REVIEW

**Comment by satriadinataaa** [comment]
In our last meeting, @rizkipraatama  said that we dont need to push env development and env production. Maybe u can ask him / @azhry  later. 

Lgtm for the other changes

**Review by azhry — COMMENTED** [review]
Please ignore `.env.development` and `.env.production` before pushing

**Review by azhry — APPROVED** [review]

**Comment by luthfi-ramadhan** [comment]
its a conflict here i cant merge this pr. since im new here, idk how to solve conflict. any idea? @LordDoraemon @azhry @rizkipraatama

**Comment by satriadinataaa** [comment]
> its a conflict here i cant merge this pr. since im new here, idk how to solve conflict. any idea? @LordDoraemon @azhry @rizkipraatama

u can merge it now

**Pull request merged**
