### PR TITLE
fix #24

### LINKED ISSUE #24: Update Design
there is some changes in design by our UI designer. please implement the changes to our website

### PR DESCRIPTION
**Pull request by satriadinataaa**
fix #24

Change text :
@Navbar : Pekerjaan -> Proyek
@ContactUs : Kualitas -> Kualitas Terpercaya
@WhyMustUs : Client -> Klien

Add margin left in medium screen @highlight

@azhry

### CODE REVIEW

**Comment by azhry** [comment]
Can you list here what are the changes ?

**Comment by satriadinataaa** [comment]
> Can you list here what are the changes ?

ofc, you can check it now on the description. Sorry.

**Review by azhry — APPROVED** [review]

**Comment by azhry** [comment]
lgtm

**Comment by satriadinataaa** [comment]
> lgtm

sry i miss one change.

@Footer :
the href @email and @phone was reference to 'sitesname/a' before. Now i fix it to 'sitesname/#'

**Pull request merged**
